---
- name: Install java8 packages
  become: True
  become_method: sudo
  apt:
    name: openjdk-8-jre
    state: latest

- name: Added java ld path
  become: True
  become_method: sudo
  copy:
    content: '/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server'
    dest: /etc/ld.so.conf.d/java.conf
  register: java_ld_path

- name: reload ldconfig
  become: True
  become_method: sudo
  shell: ldconfig
  when: java_ld_path.changed

- name: correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
